name: elektryk_website
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  auto_route: ^2.3.0
  auto_route_generator: ^2.1.0
  bloc: ^7.1.0
  build_runner: ^2.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^7.2.0
  flutter_localizations:
    sdk: flutter
  google_fonts: ^2.1.0
  intl: ^0.17.0
  lint: ^1.5.3

dev_dependencies:
  bloc_test: ^8.1.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.0
  very_good_analysis: ^2.3.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - images/
